{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "core",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.5.1.jar",
          "url": "core-1.5.1.jar",
          "size": 36720,
          "sha512": "5b75fc24b75e8f132b6c435ee4e422bebe483f34d2d6e286fca536c058baf1ed5fdc3cc9dbc96d0f05862e229a621aae01dbe59a70410b5aa10f7ffc973a3f31",
          "sha256": "66865adec58bedd2fd6f6c13a22bacfd20ca198771b49669fc53152a6b0b23c8",
          "sha1": "156c6645b97fb62be48592d57cecfc46369934bb",
          "md5": "9b9468a089dd9763be0097194902364f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.5.1.jar",
          "url": "core-1.5.1.jar",
          "size": 36720,
          "sha512": "5b75fc24b75e8f132b6c435ee4e422bebe483f34d2d6e286fca536c058baf1ed5fdc3cc9dbc96d0f05862e229a621aae01dbe59a70410b5aa10f7ffc973a3f31",
          "sha256": "66865adec58bedd2fd6f6c13a22bacfd20ca198771b49669fc53152a6b0b23c8",
          "sha1": "156c6645b97fb62be48592d57cecfc46369934bb",
          "md5": "9b9468a089dd9763be0097194902364f"
        }
      ]
    }
  ]
}
