# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enables Gradle Build Cache.
org.gradle.caching=true

# Enables Gradle Configuration Cache
org.gradle.configuration-cache=true

# Enables parallel execution of tasks across decoupled modules
org.gradle.parallel=true

# AndroidX package structure configuration
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Disable non-transitive R class generation to speed up build
android.nonTransitiveRClass=true

# Platform Versioning (Single Source of Truth)
PLATFORM_VERSION_NAME=1.4.1
PLATFORM_VERSION_CODE=25
kotlin.compiler.execution.strategy=in-process
