{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "game-challenges",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-statistics",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-achievements",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-rewards",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-challenges-1.5.1.jar",
          "url": "game-challenges-1.5.1.jar",
          "size": 55630,
          "sha512": "28ca63f637ceac1bfb046307721e6690ca7ad29289acb478a394a96d410e30e28808c612978a638f2e013bc60ab1cb68135ccf00bf70c366e72619b5cae7ce69",
          "sha256": "06052a6776ba5ada64d225d36a2288e39bf499d189c13a121fd6830bfcd06fbc",
          "sha1": "df69c8510b07d708844d6868d1112a318bd375fa",
          "md5": "011202941d0595bcdf93c65356c66c49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-statistics",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-achievements",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-rewards",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-challenges-1.5.1.jar",
          "url": "game-challenges-1.5.1.jar",
          "size": 55630,
          "sha512": "28ca63f637ceac1bfb046307721e6690ca7ad29289acb478a394a96d410e30e28808c612978a638f2e013bc60ab1cb68135ccf00bf70c366e72619b5cae7ce69",
          "sha256": "06052a6776ba5ada64d225d36a2288e39bf499d189c13a121fd6830bfcd06fbc",
          "sha1": "df69c8510b07d708844d6868d1112a318bd375fa",
          "md5": "011202941d0595bcdf93c65356c66c49"
        }
      ]
    }
  ]
}
