{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "ads",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ads-1.5.1.aar",
          "url": "ads-1.5.1.aar",
          "size": 200788,
          "sha512": "5b90bcafbf8e6a232af61d3a51c713aa170ab7afbc401c559159925f623f837404eec12ddafec857940ab5203e9e693c36f03ab00c6c36cde1cdc095f3682b01",
          "sha256": "4cab4ffa65d174bc8d83663646fdd9e3d9b6d9bce01a081f4ba3f842593b65ac",
          "sha1": "e0bc6c8f8107ed1b3fd7e9c90b365c055bd6f736",
          "md5": "d5d0771547087aba68843c658aa13f93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "ads-api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "analytics-api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.1.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ads-1.5.1.aar",
          "url": "ads-1.5.1.aar",
          "size": 200788,
          "sha512": "5b90bcafbf8e6a232af61d3a51c713aa170ab7afbc401c559159925f623f837404eec12ddafec857940ab5203e9e693c36f03ab00c6c36cde1cdc095f3682b01",
          "sha256": "4cab4ffa65d174bc8d83663646fdd9e3d9b6d9bce01a081f4ba3f842593b65ac",
          "sha1": "e0bc6c8f8107ed1b3fd7e9c90b365c055bd6f736",
          "md5": "d5d0771547087aba68843c658aa13f93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ads-1.5.1-sources.jar",
          "url": "ads-1.5.1-sources.jar",
          "size": 37569,
          "sha512": "bd868ee62a97825d47293ff54e2b37cd7d33349d120a3a4e96ec37e166b64f84bc5a63682db0677bef9fbd1bc66e710e1e1e15f122eff50157f27fd8b149a954",
          "sha256": "5555d198cb711046173c36042738228be3d1d1b17e1b594f63dd08ceea060981",
          "sha1": "122260142a606b956fc39c4aea0fc61913feca12",
          "md5": "926e6632b80fdb0d6b2beac0aa9196b7"
        }
      ]
    }
  ]
}
