{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "core-android",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-android-1.5.1.aar",
          "url": "core-android-1.5.1.aar",
          "size": 22826,
          "sha512": "25f1b983f6823264e984397b3771892933d61582f3600803d82b34088006854a8c6044f8f39c889cef1141cfadccc4637e1fb76c67d9891b6b11cef25d792121",
          "sha256": "12adbe863519e00e906618a04f6f2db1a73c8f6840186d1fae19afb327f6ab96",
          "sha1": "04e4d0c86ba4f2a83bafcebad8bf450b6e912f99",
          "md5": "a5bc44b977665740ee9f7bd9be8af1e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-android-1.5.1.aar",
          "url": "core-android-1.5.1.aar",
          "size": 22826,
          "sha512": "25f1b983f6823264e984397b3771892933d61582f3600803d82b34088006854a8c6044f8f39c889cef1141cfadccc4637e1fb76c67d9891b6b11cef25d792121",
          "sha256": "12adbe863519e00e906618a04f6f2db1a73c8f6840186d1fae19afb327f6ab96",
          "sha1": "04e4d0c86ba4f2a83bafcebad8bf450b6e912f99",
          "md5": "a5bc44b977665740ee9f7bd9be8af1e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-android-1.5.1-sources.jar",
          "url": "core-android-1.5.1-sources.jar",
          "size": 9593,
          "sha512": "afe0d6ff96c5e66df19f69b7eb990256837f9a47ab25e4299a77f75bb0b492b052e31588fafbccb2951ed70efd186556102b7eef5a048d2ad4a7dccbc725ee00",
          "sha256": "cabbb6965cdeb1cb65740a62fc6e39329cc66f73bbe11ad5e96bb8314e55ed88",
          "sha1": "ba16501f584db78ee69b7fb0decd33e0e17f39b9",
          "md5": "3f3e98e6f3c688800ddf65264754a69b"
        }
      ]
    }
  ]
}
