{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "about",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "about-1.5.1.aar",
          "url": "about-1.5.1.aar",
          "size": 81471,
          "sha512": "bc077b23c791cf80753ce6d02a7070493f6d494cb011eac50dfd4e52d008e5f5212117145d14c7e36369f5c5b793fc8013302d10b6088a1bf217cdd3c13c15c2",
          "sha256": "2ed0b9364aae920cc09df44187442bb736996a36e168a369e6c71fd39217c293",
          "sha1": "9a1a17640536d07545883145277d44c3a8c48262",
          "md5": "c1f2f454675efde463d45f162db90ca4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "designsystem",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "about-1.5.1.aar",
          "url": "about-1.5.1.aar",
          "size": 81471,
          "sha512": "bc077b23c791cf80753ce6d02a7070493f6d494cb011eac50dfd4e52d008e5f5212117145d14c7e36369f5c5b793fc8013302d10b6088a1bf217cdd3c13c15c2",
          "sha256": "2ed0b9364aae920cc09df44187442bb736996a36e168a369e6c71fd39217c293",
          "sha1": "9a1a17640536d07545883145277d44c3a8c48262",
          "md5": "c1f2f454675efde463d45f162db90ca4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "about-1.5.1-sources.jar",
          "url": "about-1.5.1-sources.jar",
          "size": 11298,
          "sha512": "781ce9efe9509ea9a6d5b7bbcf023e9ff6482356240a1a045ed6b8b7387f4befa0b6b04b8f85549cd26a8be45692d3688e3d58c925e946a3191e4399919d32fe",
          "sha256": "6abca517cbabae73927a99c971cf2fe3648939df860fd79ace0aba99afd050cd",
          "sha1": "806b41a2c6a3ad7371b9895f917bf8fd06a394cf",
          "md5": "9cd9a91488cb3e2b4fe6c3b8b4328fed"
        }
      ]
    }
  ]
}
