{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "game-haptics",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-haptics-1.5.1.jar",
          "url": "game-haptics-1.5.1.jar",
          "size": 41029,
          "sha512": "9cfafd5258cc365dc7e8540853db5404b838fab6e1e925cdea00931c8b247a7b3100b85b6bb231efcb7d471f8600fbe4c6d071fcb70c967e9168fc285b63bdd8",
          "sha256": "d3d87643c76927bda25c8250b5f439cf2210d7b8aa0b300665f9ef908132a00e",
          "sha1": "3b16388e1b323818f47b03ac5b6d3194ee662c2e",
          "md5": "376c117db3d85d4b98413bfa146d1d04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-haptics-1.5.1.jar",
          "url": "game-haptics-1.5.1.jar",
          "size": 41029,
          "sha512": "9cfafd5258cc365dc7e8540853db5404b838fab6e1e925cdea00931c8b247a7b3100b85b6bb231efcb7d471f8600fbe4c6d071fcb70c967e9168fc285b63bdd8",
          "sha256": "d3d87643c76927bda25c8250b5f439cf2210d7b8aa0b300665f9ef908132a00e",
          "sha1": "3b16388e1b323818f47b03ac5b6d3194ee662c2e",
          "md5": "376c117db3d85d4b98413bfa146d1d04"
        }
      ]
    }
  ]
}
