{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "security",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.5.1.aar",
          "url": "security-1.5.1.aar",
          "size": 16098,
          "sha512": "378db01011153fd9ccd2a71e25c0a721df6b28007a63cdf14eeba3e509e54a614bf6c9fc1060f355e69d6ce32416a068ba723e131b72657ced6107073f7749d0",
          "sha256": "a9fba498ae4d67649f9231315b57ec4ba5d0a39cd238aa1c4118f717c9bbedf6",
          "sha1": "6d06fe51d43c8fe0dc165e5c594ddd9ca7a0efff",
          "md5": "853407b71c65fef7f7330d7123f94b49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.5.1.aar",
          "url": "security-1.5.1.aar",
          "size": 16098,
          "sha512": "378db01011153fd9ccd2a71e25c0a721df6b28007a63cdf14eeba3e509e54a614bf6c9fc1060f355e69d6ce32416a068ba723e131b72657ced6107073f7749d0",
          "sha256": "a9fba498ae4d67649f9231315b57ec4ba5d0a39cd238aa1c4118f717c9bbedf6",
          "sha1": "6d06fe51d43c8fe0dc165e5c594ddd9ca7a0efff",
          "md5": "853407b71c65fef7f7330d7123f94b49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.5.1-sources.jar",
          "url": "security-1.5.1-sources.jar",
          "size": 4439,
          "sha512": "def0ff674715ec0d47e7bd0b588dd1f038bda3059954ddb0b1eb3523870642d4669a86088865996ad8c744f92d24e7c8510ab9173192f30e68c37caee33fde78",
          "sha256": "84a1d0b24aad6be654926c6872cb1aaab48e462149a328f711103479c376041a",
          "sha1": "be4757bdd0b4e278357416a073e45dfb59e2dd8a",
          "md5": "3a29267dc6c2e965a6e37dc350960935"
        }
      ]
    }
  ]
}
