{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "billing-api",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "billing-api-1.5.1.jar",
          "url": "billing-api-1.5.1.jar",
          "size": 14567,
          "sha512": "bd6a1b380e45e272848384ec1ef9100566911b20b5127ddf557fcb0b654daa89cb729198940245c702eafee0b4b76a145064a6c1d20a3f4c5d3d81c591fdbc60",
          "sha256": "1a165f13b7e37a2fcf18dc1def929aa824e8e2f38dac53ff5c017a4de51fe637",
          "sha1": "1b2d75f4d1796aa844f6515c6de41ea86e7372b6",
          "md5": "e89003ab527b2f5d21db1213e5434cdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "billing-api-1.5.1.jar",
          "url": "billing-api-1.5.1.jar",
          "size": 14567,
          "sha512": "bd6a1b380e45e272848384ec1ef9100566911b20b5127ddf557fcb0b654daa89cb729198940245c702eafee0b4b76a145064a6c1d20a3f4c5d3d81c591fdbc60",
          "sha256": "1a165f13b7e37a2fcf18dc1def929aa824e8e2f38dac53ff5c017a4de51fe637",
          "sha1": "1b2d75f4d1796aa844f6515c6de41ea86e7372b6",
          "md5": "e89003ab527b2f5d21db1213e5434cdd"
        }
      ]
    }
  ]
}
