{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "billing",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "billing-1.5.1.aar",
          "url": "billing-1.5.1.aar",
          "size": 82094,
          "sha512": "620a6552fe4ba0e2d19bb5327badc3fdf8a8d703383d96890275492654a202e67ad648a101ee1e3d427e23d074b2794d04fb5e28db9d07c9f670f70a106ce1b7",
          "sha256": "e389cb49dd871ae831b727cc8f21e9e41c56afa57138f8b9adde096ebc64f769",
          "sha1": "9239cda082eeb04ee92bd4da9d7a0877139eee96",
          "md5": "3774931e311e01ef285350449d3d1b83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "billing-api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "analytics-api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "remote-config-api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "notifications-api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "billing-1.5.1.aar",
          "url": "billing-1.5.1.aar",
          "size": 82094,
          "sha512": "620a6552fe4ba0e2d19bb5327badc3fdf8a8d703383d96890275492654a202e67ad648a101ee1e3d427e23d074b2794d04fb5e28db9d07c9f670f70a106ce1b7",
          "sha256": "e389cb49dd871ae831b727cc8f21e9e41c56afa57138f8b9adde096ebc64f769",
          "sha1": "9239cda082eeb04ee92bd4da9d7a0877139eee96",
          "md5": "3774931e311e01ef285350449d3d1b83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "billing-1.5.1-sources.jar",
          "url": "billing-1.5.1-sources.jar",
          "size": 20746,
          "sha512": "dd1b503f79aed59567fb6ada1f7d916ed838eb91ea1049c6d326fe8cac726ba3d476a0a77392682e10f2863a78c0ecca673dde8ae7be60c994986e7bab9f7b68",
          "sha256": "89020bfcfdcff20f178acf6402bc16130c5828afeb7dec89ece8c4eae783b3d7",
          "sha1": "da29546023ef9423a2eec761ff02b9dc169d9b2d",
          "md5": "9478074191af154f09030e99da344d61"
        }
      ]
    }
  ]
}
