package com.codewiththiru.platform.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import com.codewiththiru.platform.designsystem.tokens.ColorTokens

internal val LightColorScheme = lightColorScheme(
    primary = ColorTokens.md_theme_light_primary,
    onPrimary = ColorTokens.md_theme_light_onPrimary,
    primaryContainer = ColorTokens.md_theme_light_primaryContainer,
    onPrimaryContainer = ColorTokens.md_theme_light_onPrimaryContainer,
    secondary = ColorTokens.md_theme_light_secondary,
    onSecondary = ColorTokens.md_theme_light_onSecondary,
    secondaryContainer = ColorTokens.md_theme_light_secondaryContainer,
    onSecondaryContainer = ColorTokens.md_theme_light_onSecondaryContainer,
    tertiary = ColorTokens.md_theme_light_tertiary,
    onTertiary = ColorTokens.md_theme_light_onTertiary,
    tertiaryContainer = ColorTokens.md_theme_light_tertiaryContainer,
    onTertiaryContainer = ColorTokens.md_theme_light_onTertiaryContainer,
    error = ColorTokens.md_theme_light_error,
    errorContainer = ColorTokens.md_theme_light_errorContainer,
    onError = ColorTokens.md_theme_light_onError,
    onErrorContainer = ColorTokens.md_theme_light_onErrorContainer,
    background = ColorTokens.md_theme_light_background,
    onBackground = ColorTokens.md_theme_light_onBackground,
    surface = ColorTokens.md_theme_light_surface,
    onSurface = ColorTokens.md_theme_light_onSurface,
    surfaceVariant = ColorTokens.md_theme_light_surfaceVariant,
    onSurfaceVariant = ColorTokens.md_theme_light_onSurfaceVariant,
    outline = ColorTokens.md_theme_light_outline,
    inverseOnSurface = ColorTokens.md_theme_light_inverseOnSurface,
    inverseSurface = ColorTokens.md_theme_light_inverseSurface,
    inversePrimary = ColorTokens.md_theme_light_inversePrimary,
    surfaceTint = ColorTokens.md_theme_light_surfaceTint,
    outlineVariant = ColorTokens.md_theme_light_outlineVariant,
    scrim = ColorTokens.md_theme_light_scrim,
)

internal val DarkColorScheme = darkColorScheme(
    primary = ColorTokens.md_theme_dark_primary,
    onPrimary = ColorTokens.md_theme_dark_onPrimary,
    primaryContainer = ColorTokens.md_theme_dark_primaryContainer,
    onPrimaryContainer = ColorTokens.md_theme_dark_onPrimaryContainer,
    secondary = ColorTokens.md_theme_dark_secondary,
    onSecondary = ColorTokens.md_theme_dark_onSecondary,
    secondaryContainer = ColorTokens.md_theme_dark_secondaryContainer,
    onSecondaryContainer = ColorTokens.md_theme_dark_onSecondaryContainer,
    tertiary = ColorTokens.md_theme_dark_tertiary,
    onTertiary = ColorTokens.md_theme_dark_onTertiary,
    tertiaryContainer = ColorTokens.md_theme_dark_tertiaryContainer,
    onTertiaryContainer = ColorTokens.md_theme_dark_onTertiaryContainer,
    error = ColorTokens.md_theme_dark_error,
    errorContainer = ColorTokens.md_theme_dark_errorContainer,
    onError = ColorTokens.md_theme_dark_onError,
    onErrorContainer = ColorTokens.md_theme_dark_onErrorContainer,
    background = ColorTokens.md_theme_dark_background,
    onBackground = ColorTokens.md_theme_dark_onBackground,
    surface = ColorTokens.md_theme_dark_surface,
    onSurface = ColorTokens.md_theme_dark_onSurface,
    surfaceVariant = ColorTokens.md_theme_dark_surfaceVariant,
    onSurfaceVariant = ColorTokens.md_theme_dark_onSurfaceVariant,
    outline = ColorTokens.md_theme_dark_outline,
    inverseOnSurface = ColorTokens.md_theme_dark_inverseOnSurface,
    inverseSurface = ColorTokens.md_theme_dark_inverseSurface,
    inversePrimary = ColorTokens.md_theme_dark_inversePrimary,
    surfaceTint = ColorTokens.md_theme_dark_surfaceTint,
    outlineVariant = ColorTokens.md_theme_dark_outlineVariant,
    scrim = ColorTokens.md_theme_dark_scrim,
)
