{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "game-sync",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-sync-1.5.1.jar",
          "url": "game-sync-1.5.1.jar",
          "size": 38171,
          "sha512": "a49defa71c6da4369d7539e0071403c40727852d9e43af930fb7c131fce4ae66250c82f27540d79779a118032244e00b00caad883d6bbd9dd0bf691e4c28d666",
          "sha256": "25ebc97659924f4352b3314175fcdb11f027d88b93162c5e7f22f56b8ce3c5ad",
          "sha1": "dc259dca5a40afa79772108d8f9dcbbbdadbcfaf",
          "md5": "434cd444af1a42738a3d291de1c55d92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-sync-1.5.1.jar",
          "url": "game-sync-1.5.1.jar",
          "size": 38171,
          "sha512": "a49defa71c6da4369d7539e0071403c40727852d9e43af930fb7c131fce4ae66250c82f27540d79779a118032244e00b00caad883d6bbd9dd0bf691e4c28d666",
          "sha256": "25ebc97659924f4352b3314175fcdb11f027d88b93162c5e7f22f56b8ce3c5ad",
          "sha1": "dc259dca5a40afa79772108d8f9dcbbbdadbcfaf",
          "md5": "434cd444af1a42738a3d291de1c55d92"
        }
      ]
    }
  ]
}
