{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "updates",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "updates-1.5.1.aar",
          "url": "updates-1.5.1.aar",
          "size": 75272,
          "sha512": "98a2e8d721f18cf9508749b5349131132a30a101ce8253d59f7c63dcb2fb2205f93a8ce3fd5e923c20547c2abb16887c56bf30b013cfbf03419f9a485948cfbf",
          "sha256": "dbd33eaa6c229e6670dac1dfb0e5b6e2ec82cd00c53faf01b9adc1db28cdeb17",
          "sha1": "eb77bdcf62707c77d655eaa1a89ac80e7355cd57",
          "md5": "42f48928ddd1ee388b44773baccb8a79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "designsystem",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.google.android.play",
          "module": "app-update-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "updates-1.5.1.aar",
          "url": "updates-1.5.1.aar",
          "size": 75272,
          "sha512": "98a2e8d721f18cf9508749b5349131132a30a101ce8253d59f7c63dcb2fb2205f93a8ce3fd5e923c20547c2abb16887c56bf30b013cfbf03419f9a485948cfbf",
          "sha256": "dbd33eaa6c229e6670dac1dfb0e5b6e2ec82cd00c53faf01b9adc1db28cdeb17",
          "sha1": "eb77bdcf62707c77d655eaa1a89ac80e7355cd57",
          "md5": "42f48928ddd1ee388b44773baccb8a79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "updates-1.5.1-sources.jar",
          "url": "updates-1.5.1-sources.jar",
          "size": 15143,
          "sha512": "f4f6afb0c475ba7756105106503fb0e5069e734021d16c81292de5d0f71b4d1b06b8d569df7e6f85ca6a13fee75c336ede95339b8d15a279434ef901b62dbaab",
          "sha256": "e86b4c4233940d2ef36deeb871e9142d3bec763958ae56ddc22bb29701f71897",
          "sha1": "49ff60c89a521c4389e8849d3e411d08793a9496",
          "md5": "e81c77373941bcdace0afdc48363d6d8"
        }
      ]
    }
  ]
}
