{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "game-leaderboard",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-sync",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-profile",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-leaderboard-1.5.1.jar",
          "url": "game-leaderboard-1.5.1.jar",
          "size": 44028,
          "sha512": "23f4afee93cb1e33e6506c5446e66b6837941fc5eec60329f3fe8e56534def3ae08dd4f7a01b41fc1fe7c2ce7f5b582904ff1732ec1f1e4e68940b0573ca0494",
          "sha256": "7ba5807f6a8ae76b56e5919e934a59d0879d8f5f99fe6759682d9a1cf75f4b88",
          "sha1": "fc453e53001d1f4a055d8274898f209e526f9ff1",
          "md5": "29b022c800a4d479bf5213a8cbbaf72b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-sync",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-profile",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-leaderboard-1.5.1.jar",
          "url": "game-leaderboard-1.5.1.jar",
          "size": 44028,
          "sha512": "23f4afee93cb1e33e6506c5446e66b6837941fc5eec60329f3fe8e56534def3ae08dd4f7a01b41fc1fe7c2ce7f5b582904ff1732ec1f1e4e68940b0573ca0494",
          "sha256": "7ba5807f6a8ae76b56e5919e934a59d0879d8f5f99fe6759682d9a1cf75f4b88",
          "sha1": "fc453e53001d1f4a055d8274898f209e526f9ff1",
          "md5": "29b022c800a4d479bf5213a8cbbaf72b"
        }
      ]
    }
  ]
}
