{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codewiththiru.platform",
    "module": "game-statistics",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-events",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-statistics-1.5.1.jar",
          "url": "game-statistics-1.5.1.jar",
          "size": 43182,
          "sha512": "146e9c0e7dfd180d788e5f27774fb7e011bdf8475965c02f696b3ab5bd7a0f8563072ad9555fcccc4ff7d599ae1490712483558e18f146da33c01dbfa6616d04",
          "sha256": "094b5a27301b595a8980e56910500fdf67523c781f00b2712bea555a42ea52ec",
          "sha1": "18e36a9020c60f971e42acb45f0ef83f5c61f7bc",
          "md5": "a72a12b495a3551c29092b1a1aadeb05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-save",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.codewiththiru.platform",
          "module": "game-events",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "game-statistics-1.5.1.jar",
          "url": "game-statistics-1.5.1.jar",
          "size": 43182,
          "sha512": "146e9c0e7dfd180d788e5f27774fb7e011bdf8475965c02f696b3ab5bd7a0f8563072ad9555fcccc4ff7d599ae1490712483558e18f146da33c01dbfa6616d04",
          "sha256": "094b5a27301b595a8980e56910500fdf67523c781f00b2712bea555a42ea52ec",
          "sha1": "18e36a9020c60f971e42acb45f0ef83f5c61f7bc",
          "md5": "a72a12b495a3551c29092b1a1aadeb05"
        }
      ]
    }
  ]
}
