name: Prod Release & Publish

on:
  push:
    branches: [ prod ]

permissions:
  contents: write
  packages: write

jobs:
  validate-and-publish:
    name: Validate & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Run Checks
        run: ./gradlew lintDebug testDebugUnitTest assembleRelease
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Binary Compatibility Checks
        run: ./gradlew apiCheck
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Artifacts
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}
