name: Prod Release & Publish

on:
  push:
    branches: [ prod ]

permissions:
  contents: write
  packages: write

jobs:
  validate-and-publish:
    name: Validate & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Run Checks
        run: ./gradlew lintDebug testDebugUnitTest assembleRelease detekt ktlintCheck

      - name: Run Binary Compatibility Checks
        run: ./gradlew apiCheck
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}


      - name: Auto-Update README Version
        run: |
          VERSION=$(grep -E '^PLATFORM_VERSION_NAME=' gradle.properties | cut -d '=' -f 2)
          sed -i -E "s/## Version: v[0-9]+\.[0-9]+\.[0-9]+/## Version: v$VERSION/" README.md
          sed -i -E "s/platform-bom:[0-9]+\.[0-9]+\.[0-9]+/platform-bom:$VERSION/" README.md

      - name: Commit README Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-sync version in README [skip ci]"
          branch: prod
          file_pattern: "README.md"
